name: ci

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: 'true'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: cargo clippy
        run: cargo clippy --features async --no-deps -- -D warnings

      - name: cargo fmt
        run: cargo fmt -- --check

      - name: cargo doc
        run: cargo doc --features async --no-deps --document-private-items
        env:
          RUSTDOCFLAGS: -D warnings

  test:
    name: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            ort_dylib_path: ./runtimes/libonnxruntime.linux-x64-1.18.0.so
          - os: macos-latest
            ort_dylib_path: ./runtimes/libonnxruntime.osx-arm64-1.18.0.dylib
          - os: windows-latest
            ort_dylib_path: ./runtimes/libonnxruntime.win-x64-1.18.0.dll
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: compile
        run: cargo test --features async --no-run

      - name: test
        run: cargo test --features async
        env:
          ORT_DYLIB_PATH: ${{ matrix.ort_dylib_path }}